apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -dev
namespace: my-app-dev
resources:
  - ../../base
images:
  - name: tegar900/my-app
    newTag: v1.0.1
configMapGenerator:
  - name: my-app-config
    literals:
      - ENV=dev