apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: my-app-dev
resources:
  - ../../base
  - ingress.yaml
images:
  - name: tegar900/my-app
    newTag: dev
configMapGenerator:
  - name: my-app-config
    literals:
      - ENV=dev
# patches:
#   - target:
#       kind: Service
#       name: my-app
#     patch: |-
#       - op: add
#         path: /spec/ports/0/nodePort
#         value: 30080