apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: my-app-staging
resources:
  - ../../base
  - ingress.yaml
images:
  - name: tegar900/my-app
    newTag: staging
configMapGenerator:
  - name: my-app-config
    literals:
      - ENV=staging
