apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: my-app-prod
resources:
  - ../../base
  # - ingress.yaml
images:
  - name: tegar900/my-app
    newTag: v1.0.6
configMapGenerator:
  - name: my-app-config
    literals:
      - ENV=prod
